// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PCBuilder.Data;

#nullable disable

namespace PCBuilder.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260225160838_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("PCBuilder.Models.CPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("BaseFrequency")
                        .HasColumnType("REAL");

                    b.Property<int>("Cores")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasIGPU")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Socket")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TDP")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Threads")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "Intel Core i5-10400F",
                            PerformanceScore = 40,
                            Price = 12000m,
                            Socket = "LGA1200",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 2,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "AMD Ryzen 5 5600x",
                            PerformanceScore = 25,
                            Price = 16000m,
                            Socket = "AM4",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 3,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "Intel Core i9-14900K",
                            PerformanceScore = 100,
                            Price = 65000m,
                            Socket = "LGA1700",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 4,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "AAAAA",
                            PerformanceScore = 100,
                            Price = 444m,
                            Socket = "LGA1700",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 5,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "BBBBB",
                            PerformanceScore = 100,
                            Price = 666m,
                            Socket = "LGA1700",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 6,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "CCCCCCCC",
                            PerformanceScore = 100,
                            Price = 777m,
                            Socket = "LGA1700",
                            TDP = 0,
                            Threads = 0
                        },
                        new
                        {
                            Id = 7,
                            BaseFrequency = 0.0,
                            Cores = 0,
                            HasIGPU = false,
                            Name = "DDDD",
                            PerformanceScore = 100,
                            Price = 888m,
                            Socket = "LGA1700",
                            TDP = 0,
                            Threads = 0
                        });
                });

            modelBuilder.Entity("PCBuilder.Models.GPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PerformanceScore")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "NVIDIA RTX 5090",
                            PerformanceScore = 100,
                            Price = 16000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
